#!/bin/sh -e

export XDG_RUNTIME_DIR="/run/user/$(id -u)"

. env.sh

mkdir -p "${XDG_RUNTIME_DIR}/snap.weston"

mkdir -p "${XDG_CACHE_HOME}"
mkdir -p "${XDG_CONFIG_HOME}/weston/"

exec "$SNAP/usr/bin/weston-launch" "$@"
