name: weston
base: core18
version: '7.0.0-12'
summary: reference implementation of a wayland compositor (experimental)
description: |
  Part of the Wayland project is also the Weston reference implementation
  of a Wayland compositor. Weston can run as an X client or under Linux
  KMS and ships with a few demo clients. The Weston compositor is a minimal
  and fast compositor and is suitable for many embedded and mobile use
  cases.

# icon: weston.png

# architectures:
#   - build-on: [amd64, i386]
#     run-on: [amd64, i386]

#adopt-info: devmode # use 'strict' once you have the right plugs and slots

grade: stable
confinement: devmode # use 'strict' once you have the right plugs and slots

environment:
  SHELL: bash
  #
  LC_ALL: C.UTF-8
  LD_LIBRARY_PATH: ${SNAP}/usr/lib:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/lib:${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}
  PATH: $SNAP/bin:$SNAP/usr/bin:${PATH}
  # Snap compatibality
  SNAPCRAFT_ARCH_TRIPLET: ${SNAPCRAFT_ARCH_TRIPLET}

  # -- Xkb-Library ---
  XKB_CONFIG_ROOT: ${SNAP}/usr/share/X11/xkb
  # XKB_LOG_LEVEL: 50
  # XKB_LOG_VERBOSITY: 10

  # --- XDG config ---
  XDG_CACHE_HOME:  ${SNAP_USER_COMMON}/.cache
  XDG_CONFIG_DIRS: ${SNAP}/etc/xdg #:$XDG_CONFIG_DIRS
  XDG_CONFIG_HOME: $SNAP_USER_DATA/.config

  # --- Prep EGL ---
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LIBVA_DRIVERS_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
 
  # --- Prep GDK ---
  GDK_PIXBUF_BINARY_VERSION: '2.10.0' # FIXME: how to get this from installed version ?
  GDK_BACKEND: wayland
  # FIXME: loaders.cache should be created after install/refresh
  GDK_PIXBUF_MODULEDIR: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/${GDK_PIXBUF_BINARY_VERSION}/loaders/
  # FIXME: generate loaders.cache file ?!
  # with: gdk-pixbuf-query-loaders > $libdir/gdk-pixbuf-2.0/$binary_version/loaders.cache
  GDK_PIXBUF_MODULE_FILE: ${SNAP_USER_COMMON}/gdk-pixbuf-2.0/${GDK_PIXBUF_BINARY_VERSION}/loaders.cache

  # --- Qt ---
  QT_DEBUG_PLUGINS: 1
  # QTVER: qt5
  QT_QPA_PLATFORM_PLUGIN_PATH: ${SNAP}/usr/lib/x86_64-linux-gnu/qt5/plugins
  #QT_PLUGIN_PATH: $QTDIR/lib/plugins/
  QT_PLUGIN_PATH: ${SNAP}/usr/lib/x86_64-linux-gnu/qt5/plugins # FIXME: is this needed ?

  # --- Setup Weston ---
  # WESTON_DATA_DIR: 
  # WAYLAND_DEBUG: 1
  # WAYLAND_DISPLAY: 

  # WESTON_CONFIG_FILE
  WESTON_LIBINPUT_LOG_PRIORITY: debug
  # WESTON_DATA_DIR
  # WESTON_CONFIG_FILE_ENV_VAR
  # TODO: this is set in startup-script
  #WESTON_MODULE_MAP: drm-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/drm-backend.so;fbdev-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/fbdev-backend.so;gl-renderer.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/gl-renderer.so;headless-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/headless-backend.so;wayland-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/wayland-backend.so;x11-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/x11-backend.so;xwayland.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/xwayland.so;desktop-shell.so:${SNAP}/usr/lib/x86_64-linux-gnu/weston/desktop-shell.so
  #WESTON_MODULE_MAP: drm-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/drm-backend.so;fbdev-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/fbdev-backend.so;gl-renderer.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/gl-renderer.so;headless-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/headless-backend.so;wayland-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/wayland-backend.so;x11-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/x11-backend.so;xwayland.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/xwayland.so;desktop-shell.so:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/weston/desktop-shell.so


  WESTON_MODULE_MAP: ""
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};weston-desktop-shell=${SNAP}/usr/libexec/weston-desktop-shell"

  ## FIXME: TODO: ivi is configureable !
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};weston-ivi-shell-user-interface=${SNAP}/usr/libexec/weston-ivi-shell-user-interface"
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};weston-keyboard=${SNAP}/usr/libexec/weston-keyboard"

  ## FIXME: TODO: weston-screenshooter is also configurable !
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};weston-screenshooter=${SNAP}/usr/libexec/weston-screenshooter"
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};weston-simple-im=${SNAP}/usr/libexec/weston-simple-im"

  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};desktop-shell.so:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/weston/desktop-shell.so"

  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};fbdev-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/fbdev-backend.so"
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};gl-renderer.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/gl-renderer.so"
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};headless-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/headless-backend.so"
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};wayland-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/wayland-backend.so"
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};x11-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/x11-backend.so"
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};xwayland.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/xwayland.so"
  WESTON_MODULE_MAP: "${WESTON_MODULE_MAP};drm-backend.so=${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/libweston-7/drm-backend.so"

apps:
  weston:
    command: usr/bin/weston
    aliases: [ weston ]
    desktop: usr/share/wayland-sessions/weston.desktop
    extensions:
      - gnome-3-28
  weston-launch: 
    command: usr/bin/weston-launch
    aliases: [ weston-launch ]
    extensions:
      - gnome-3-28
  # wcap-decode:
  #   command: usr/bin/wcap-decode
  weston-info:
    command: usr/bin/weston-info
    aliases: [ weston-info ]
  weston-terminal:
    command: usr/bin/weston-terminal
    aliases: [ weston-terminal ]

    # adapter: full
 
## TODO: not enabled, because snap-store does not accept unknown interfaces :-(
# slots:
#   wayland-server:
#   xwayland: # INFO: new name for `x11` provider:

plugs:
  wayland:
  x11:
  desktop:
  desktop-legacy:
  opengl:
  framebuffer:
  # dbus:
  # locale-control:
  login-session-control:
  home:
  network:
  mount-observe:
  network-observe:
  system-observe:
  # removable-media:
  # alsa:
  # pulseaudio:

build-packages:
  - cmake # meson likes cmake
  - pkgconf
  - quilt
  - ctags

parts:
  externals:
    plugin: dump
    source: .
    organize: 
      weston/weston.ini: etc/xdg/weston/weston.ini # FIXME: replace SNAPCRAFT_ARCH_TRIPLET in config on install

  wayland-protocols:
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: '1.18'
    source-depth: 1
    plugin: autotools
    configflags: [ --prefix=/usr ]
    build-packages:
      - libwayland-bin

  weston:
    after: [ wayland-protocols ]
    #source: https://salsa.debian.org/xorg-team/wayland/weston.git
    #source-tag: 'weston-6.0.1-2'
    source: https://github.com/wayland-project/weston.git
    source-tag: 7.0.0
    source-depth: 1
    plugin: meson
    meson-parameters: 
      - --prefix=/usr
      - -Dbackend-drm=true
      - -Dbackend-drm-screencast-vaapi=false
      - -Dbackend-headless=false
      - -Dbackend-rdp=false
      - -Dscreenshare=false
      - -Dbackend-wayland=true
      - -Dbackend-x11=true
      - -Dbackend-fbdev=true
      # - -Dbackend-default=auto
      - -Drenderer-gl=true
      - -Dweston-launch=true
      - -Dxwayland=true
      # - -Dxwayland-path
      - -Dsystemd=true
      - -Dremoting=false
      - -Dpipewire=false
      #- -Dshell-desktop=true
      #- -Dshell-fullscreen=true
      #- -Dshell-ivi=true
      #- -Ddesktop-shell-client-default=weston-desktop-shell
      - -Dcolor-management-lcms=false
      - -Dcolor-management-colord=false
      - -Dlauncher-logind=true ## INFO: important, if d-bus logind
      - -Dimage-jpeg=true
      - -Dimage-webp=true
      #- -Dtools=[ 'calibrator', 'debug', 'info', 'terminal', 'touch-calibrator' ]
      #      
      - -Dsimple-dmabuf-drm=intel ## FIXME:
      - -Ddemo-clients=false
      #- -Dsimple-clients=['all']
      - -Dresize-pool=false
      - -Dwcap-decode=false
      - -Dtest-junit-xml=false
      - -Ddoc=false
      # -Dimage-webp=false
    # configflags: 
    #   - --prefix=/usr
    #install-via: prefix
    #configflags: [ "--libdir=/snap/weston/current/usr/lib" ]
    build-packages:
      - pkgconf
      - libdbus-1-dev
      - libpixman-1-dev
      - libpng-dev
      - libjpeg-dev
      - libcolord-dev
      - libwebp-dev
      - liblcms2-dev
      - mesa-common-dev
      # - libpipewire-0.2-dev
      - libglu1-mesa-dev
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libxcb1-dev
      - libxcb-composite0-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libxcb-xkb-dev
      - libx11-xcb-dev
      - libx11-dev
      - libudev-dev
      - libdrm-dev
      - libgbm-dev
      - libxkbcommon-dev
      - libcairo2-dev
      - libpango1.0-dev
      - libgdk-pixbuf2.0-dev
      - libxcursor-dev
      - libpam0g-dev
      - libvpx-dev
      - libsystemd-dev
      - libinput-dev
      # - wayland-protocols
      ## libweston:
      - libwayland-dev
    stage-packages:
      - libcairo2
      - libcolord2
      - libwebp6
      - libdatrie1
      - libevdev2
      - libfontconfig1
      - libfreetype6
      - libgles2
      - libgraphite2-3
      - libgudev-1.0-0
      - libharfbuzz0b
      - libinput10
      - libjpeg-turbo8
      - liblcms2-2
      - libmtdev1
      - libpam-modules
      - libpam-systemd
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      # - libpipewire-0.2-1
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwacom2
      - libxcb-composite0
      - libxcb-render0
      - libxcb-shm0
      - libxcb-xkb1
      - libxcursor1
      - libxkbcommon0
      - libxrender1


  # mesa:
  #   plugin: nil
  #   stage-packages:
  #     - libegl-mesa0
  #     - libegl1-mesa
  #     - libgl1-mesa-dri
  #     - libwayland-egl1-mesa
  #     - libglu1-mesa
  #     - mesa-va-drivers
  #     - mesa-vdpau-drivers
  #     - mesa-vulkan-drivers
  #     - libglx-mesa0
  #     - libglw1-mesa

  egl:
    plugin: nil
    stage-packages:
      - libglvnd0
      - libegl1
      - libvdpau-va-gl1
      #- libvdpau1
      #- libva-drm2
      #- vdpau-driver-all
      #- va-driver-all

      # libxcb-dri2-0
      # libxcb-dri3-0


## ==========================
## Testing packages
## ==========================

  testing:
    plugin: nil
    stage-packages:
      # - fontconfig
      # - fontconfig-config
      # - libfontconfig1
      - rxvt-unicode
      - x11-apps
      - stterm
      - surf
      - xterm
      - lxterminal
      - qterminal
      - gnome-terminal
      # - suckless-tools
      # - mate-themes
      # - mate-backgrounds
      # TODO: dev-headers ? or not needed ?
      - shared-mime-info
      - libjpeg8
      - libpng16-16
      - libtiff5


  common:
    plugin: nil
    stage-packages:
      # TODO: dev-headers ? or not needed ?
      - shared-mime-info
      - libjpeg8
      - libpng16-16
      - libtiff5
    override-stage: |
      set -eux
      update-mime-database ${SNAPCRAFT_STAGE}/usr/share/mime
      snapcraftctl stage

  x11:
    plugin: nil
    stage-packages:
      - rxvt-unicode
      - x11-apps
      - xterm

  gtk:
    plugin: nil
    stage-packages:
      - gnome-terminal
      - gir1.2-glib-2.0
      #
      - lxterminal

  qt:
    plugin: nil
    stage-packages:
      - qtwayland5
      - qterminal


  # wayland:
  #   plugin: nil
  #   stage-packages:
  #     - libwayland-egl1 
  #     - libwayland-client0
  #     - libwayland-cursor0
  #     - libwayland-server0
